### ISSUE TITLE
Contribution to your form-generator

### ISSUE THREAD

**Issue by edemiguel** [jguerinet/form-generator#24]
Hi Julian,
My name is Enrique de Miguel and I like your android form generator. I was wondering if you accept contributions to your project. I've got a few ideas and I would like to develop some of them.
I hope to hear from you soon.

Regards
Enrique de Miguel

**Comment by jguerinet** [comment]
Hi Enrique, 

Sorry for responding so late, I've been on vacation. Yes of course, this is my first open source project and I am quite busy on the side so I might take a bit of time to integrate your contributions but they are more than welcome. 

Julien
