### ISSUE TITLE
onClick gives warning when defining onClick out of

### ISSUE THREAD

**Issue by aiavci** [jguerinet/form-generator#39]
**Version** 4.0.1

**Description**
Compiler gives the warning `Unchecked call to 'onClick(Function1<? super T, Unit>)' as a member of raw type 'com.guerinet.fg.base.BaseTextViewItem'` when adding an `onClick` listener to a form item. This warning doesn't occur when the`onClick` is added via method chaining.

**Code**
```
BaseTextViewItem exampleItem= fg.text()
        .text("Form Item: Button")
        .icon(Position.START, R.drawable.ic_info, false)
        .icon(Position.END, R.drawable.ic_chevron_right)
        .build();

exampleItem.onClick(item -> {
    Toast.makeText(this, "Form Item: Button Clicked", Toast.LENGTH_SHORT).show();
    return Unit.INSTANCE;
});
```

**Comment by jguerinet** [comment]
This is because you're referencing a `BaseTextViewItem` instead of a `TextViewItem`. All of the `Base` classes are there to ensure that the common methods for the different subclasses are present, but should not be used directly.
